version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # mysql:
  #   image: mysql:5
  #   environment:
  #     - MYSQL_DATABASE=my_db
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=123456
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #     # se comunica con el servidor mysql a traves de la red interna de docker 
  #     # es una caracteristica de esta imagen 
  #     - PMA_HOST=mysql
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mysql